inherit_from:
  - https://raw.githubusercontent.com/Uqido/uqido-linters-config/master/.rubocop.base.yml

Style/BracesAroundHashParameters:
  Enabled: false

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/LineLength:
  Enabled: false
  Max: 120
